.TH __NAME_UPPER__ 1 "@DATE@" "__NAME__ @VERSION@" "User Commands"
.SH NAME
__NAME__ \- greet everyone listed in a Lua config
.SH SYNOPSIS
.B __NAME__
.RB [ \-h ]
.RB [ \-v ]
.RB [ \-c
.IR file ]
.SH DESCRIPTION
.B __NAME__
prints a greeting for every name in its config, as many times as the config
says.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show the help and exit.
.TP
.BR \-v ", " \-\-version
Show the version and exit.
.TP
.BR \-c ", " \-\-config " " \fIfile\fR
Read the config from
.I file
instead of the default ones.
.SH FILES
The first of these that exists is the config. If none does, the defaults are
used.
.TP
.I $XDG_CONFIG_HOME/__NAME__/config.lua
.RI ( ~/.config/__NAME__/config.lua
if XDG_CONFIG_HOME is not set)
.TP
.I ./config.lua
.SH CONFIGURATION
The config is a Lua 5.1 file that defines a
.B Config
table. Every field is optional:
.PP
.RS
.nf
Config = {
    greeting = "Hello",           -- default "Hello"
    times = 1,                    -- default 1
    names = { "world", "you" },   -- default { "world" }
}
.fi
.RE
.SH EXIT STATUS
0 on success, 1 if the arguments or the config are wrong.
.SH AUTHOR
Hugo Coto Florez <hugocoto100305@gmail.com>
.SH SEE ALSO
.BR lua (1)
